export default [
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "Once upon a time a guild from San Francisco planned to expand Northwards into the Kingdom of Canada.",
  " ",
  " ",
  " ",
  "They sent scouts out ahead in search of a wizard possessing a very rare and potent set of skills.",
  " ",
  "One talented scout happened upon a small gathering of wizards in the astral realm.",
  "This where they learned of the magnificent...",
  " ",
  " ",
  "~Magic Mike~",
  " ",
  "The guild immediately sent one of their top disciples to test the claims of my fame.",
  "With a small sampling of spells, they were quickly convinced of my powers.",
  "Yet still, could I be the wizard they'd been searching for?",
  " ",
  "They promptly summoned a winged beast to bring to to their lands and lodged me in the highest tower in the central district.",
  " ",
  "The following morning I was introduced to the Guild-master who happily challenged me with a riddle:",
  " ",
  " ",
  "\"Imagine for a moment a single table ~ Ten thousand long!\"",
  " ",
  " ",
  "\"What do you think such a table would feel like?\"",
  "\"How would you describe the experience of...\"",
  "\"PREPOSTEROUS!\" I exclaimed! \"No such table exists, nor should it! And even if it did exist, the experience would be horrible!\"",
  "The Guild-master grinned and exchanged a quick glance with his disciple before pressing further...",
  "\"Forget Ten Thousand then.\"",
  "\"Make it a Hundred Thousand!\"",
  "\"A Million!!!\"",
  "\"Anything for that Matter...  The number isn't important!\"",
  "\"Y... You.. You speak of An Infinite table?!?\" I stammered",
  " ",
  " ",
  " ",
  " ",
  "\"Precisely\" he stated with a stern look.",
  " ",
  " ",
  "Over many long hours, the Guild-master and a small fleet of his disciples unveiled the secrets and truths of their newest form of arcane magic...",
  " ",
  " ",
  " ",
  " ",
  "Magic I present you with now...",
  " ",
  " ",
  "{ Accept the magic cookies to begin }",
  " ",
  " ",
  " ",
  "{ The magic cookies are waiting above }",
  " ",
  " ",
  "{ Scroll up > Magic cookies > Begin }",
  " ",
  " ",
  "Well I wasn't prepared for this.  Back to start I suppose",
  " ",
  " ",
  " ",
  " ",
]