export default [
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "Once upon a time a guild from San Francisco planned to expand Northwards into the Kingdom of Canada.",
  " ",
  "They sent scouts out ahead in search of wizards possessing a very rare and potent set of skills.",
  " ",
  "One of their scouts found a small gathering of wizards using a portal into the astral realm.",
  "That's where the guild first learned about the amazing...",
  " ",
  " ",
  " ",
  "~Magic Mike~",
  " ",
  " ",
  "As if in disbelief, they sent their top apprentice to evaluate my fame.",
  "With afew waves of the hand and some freshly mastered spells, I quickly assuaged their fears.",
  " ",
  " ",
  "Might I be the one they've been looking for???",
  " ",
  " ",
  "They promptly summoned me to their lands in short order arranging for my travels by winged beast and generously lodging me in the highest tower in the Lower Plains.",
  " ",
  "The following morning I was introduced to the Guild-master who promptly presented me with a riddle:",
  " ",
  " ",
  "\"I want you to imagine for me a table - Ten thousand long.\"",
  " ",
  " ",
  "\"What do you think such a table would feel like?\"",
  "\"Describe the experience of using a table...\"",
  "\"PREPOSTEROUS!\" I exclaimed! \"No such table exists, nor should it!\"",
  "I continued with fervor, \"And even if it did exist, the experience would be horrible!\"",
  "The Guild-master grinned and exchanged a glance with his disciple before pressing on...",
  "\"Forget Ten Thousand then. Make it a Hundred Thousand!\"",
  "\"A Million!!!\"",
  "\"Anything for that Matter...  The number isn't important!\"",
  "\"Y... You.. You speak of An Infinite table?!?\" I stammered",
  " ",
  " ",
  " ",
  " ",
  "\"Precisely\" he stated with a stern look.",
  " ",
  " ",
  "Over many long hours, the Guild-master and a small fleet of his disciples unveiled the secrets of their newest form of arcane magic...",
  " ",
  " ",
  " ",
  " ",
  "Magic I present you with you now...",
  " ",
  " ",
  "Accept the cookies to begin",
  " ",
  " ",
  " ",
  " ",
  " ",
  "Please accept cookies to see the magic table",
  " ",
  " ",
  " ",
  " ",
  "I implore you, accept the cookies so that we may get started",
  " ",
  " ",
  " ",
  " ",
  "EAT THE WRETCHED COOKIES ALREADY!!!",
  " ",
  " ",
  " ",
  "Look, I'm really proud of the cookies so please humor me by eating some so we can both move on with our lives.",
  " ",
  " ",
  " ",
  " ",
  "Alright, I'll admit it.  I conjured this particular scroll from an older scroll that didn't age well.  I didn't have the time to make the necessary enhancements for you so it's necessary to accept the cookies before we begin.",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "Fine!  Suit yourself.  I'll just bore you with my story once more.",
  " ",
  " ",
  " ",
  " ",
]